version: '3.8'

services:
  app:
    build: .
    ports:
      - "5021:5021"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
      - API_KEY=your_api_key_here
      - DEBUG=True
      - HOST=0.0.0.0
      - PORT=5021
    depends_on:
      - db
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: unless-stopped

volumes:
  postgres_data: